# Generated by Django 4.2.5 on 2023-09-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(default='Other', max_length=75),
            preserve_default=False,
        ),
    ]
