# Generated by Django 4.2.5 on 2023-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_article_title_article_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(null=True, to='api.review'),
        ),
    ]
