# Generated by Django 4.2.5 on 2023-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_article_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(default=None, to='api.review'),
        ),
    ]
