# Generated by Django 4.2.5 on 2023-10-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_article_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/eogoiero', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
