# Generated by Django 4.2.5 on 2023-10-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_wiparticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='api.review'),
        ),
    ]
